version: '2'
services:
  e_commerce_app-app:
    image: e_commerce_app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://e_commerce_app-postgresql:5432/e_commerce_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  e_commerce_app-postgresql:
    extends:
      file: postgresql.yml
      service: e_commerce_app-postgresql
