version: '2'
services:
  e_commerce_app-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/e_commerce_app/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=e_commerce_app
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
